FROM nginx:stable-alpine
LABEL org.opencontainers.image.source="https://github.com/ranbirsingh0091/turiba-devops-labs"
LABEL org.opencontainers.image.description="Lab 1 by Ranbir Singh<"
COPY index.html /usr/share/nginx/html/index.html
EXPOSE 80